### ISSUE TITLE
Support for search query param in url

### ISSUE THREAD

**Issue by pomdtr** [Pondorasti/raycast-marketplace#20]
It would be useful to be able to launch a search on your marketplace directly from raycast by passing the query as a param.

Ex: https://scriptcommands.com?s={query}

**Comment by Pondorasti** [comment]
Shipped it! You can try it for yourself: https://scriptcommands.com/?search=achille%20lacoin

**Comment by Pondorasti** [comment]
Bonus, created a [script command](https://github.com/raycast/script-commands/pull/509) that uses the new query feature.

**Comment by pomdtr** [comment]
Thanks a lot :)
