### ISSUE TITLE
Query text not visible in firefox (dark mode)

### ISSUE THREAD

**Issue by pomdtr** [Pondorasti/raycast-marketplace#27]
See image for ref, the text is black on a black background.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/17577332/125696028-1558bd4f-540b-4f1d-985d-ba4d35430cd9.png">

**Comment by Pondorasti** [comment]
Interesting, out of all the browsers Firefox decided to say _no_! Will investigate more...

**Comment by Pondorasti** [comment]
Fixed in #28! There's also some new goodies part of this release 👀
